language: go

go:
  - "1.9.x"
  - master

before_script:
  - test-reporter before-build
script:
  - go test -coverprofile c.out
after_script:
  - test-reporter after-build --coverage-input-type gocov --exit-code $TRAVIS_TEST_RESULT
after_success:
    # Merge all coverage reports located in subdirectories and put them under: gover.coverprofile
    - gover

    # Send code coverage report to coveralls.io
    - goveralls -service=travis-ci -coverprofile=gover.coverprofile