language: go

go:
  - "1.9.x"
  - master

before_script:
    # Print buld info.
    - echo $TRAVIS_COMMIT
    - echo $TRAVIS_TAG
    - echo $TRAVIS_BRANCH
    - echo $TRAVIS_BUILD_NUMBER
    - echo $TRAVIS_REPO_SLUG

script:
    - go build
    - go test
after_success:
    # Merge all coverage reports located in subdirectories and put them under: gover.coverprofile
    - gover

    # Send code coverage report to coveralls.io
    - goveralls -service=travis-ci -coverprofile=gover.coverprofile